source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GSAnalysis_Example', :exclusive => true do
  pod "GSAnalysis", :path => "../"
end

target 'GSAnalysis_Tests', :exclusive => true do
  pod "GSAnalysis", :path => "../"
  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
